version: '2'

services:
  productapi:
    image: productapi
    build:
      context: ./../Services/ProductAPI
      dockerfile: Dockerfile
    depends_on:
      - sql.data
      - rabbitmq

   sql.data:
    image: microsoft/mssql-server-linux

  rabbitmq:
    image: rabbitmq
    ports:
      - "5672:5672"
